name: "Regression Testing"
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        if: github.event.pull_request.merged == true
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 

      - name: Run tests
        run: |
          LABEL_NAME="regression testing"
          PR_NUMBER=${{ github.event.pull_request.number }}
          LABELS_JSON=$(gh pr view $PR_NUMBER --json labels -q '.labels[].name')
          if echo "$LABELS_JSON" | grep -q "$LABEL_NAME"; then
            echo "Running regression tests..."
            # Run your tests here
          else
            echo "Skipping regression tests..."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
