name: "Run on Specific Label"
on:
  pull_request:
    types:
      - labeled

jobs:
  run-on-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for label
        run: |
          LABEL_NAME="Regression Testing"  # Replace with your specific label
          PR_LABELS="${{ github.event.pull_request.labels.*.name }}"
          if echo "${PR_LABELS[@]}" | grep -q -w "$LABEL_NAME"; then
            echo "Regression Testing label is present. Continue with workflow..."
            # Continue with your workflow steps here
          else
            echo "Regression Testing label is not present. Failing workflow..."
            exit 1
          fi
          
