name: Check PR Body

on:
  pull_request:
    types: [opened]

jobs:
  check-body:
    runs-on: ubuntu-latest
    steps:
    - name: Get PR body
      id: pr
      uses: octokit/request-action@v2.x
      with:
        route: GET /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}
        mediaType: application/vnd.github.v3+json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for name
      run: |
        BODY="${{ fromJson(steps.pr.outputs.data).body }}"
        NAME=$(echo "$BODY" | grep -oP 'name:\s*\*\K(.+?)(?=\*)')
        if [ -z "$NAME" ]; then
          echo "Name is missing in the PR body"
          exit 1
        fi
