name: Update PR Description
 
on:
  pull_request:
    types: [opened, edited, synchronize]
 
jobs:
  update_pr_description:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Extract values from file
        run: |
          # Extract name and namespace from your file (replace commands with actual commands for your file)
          name=$(grep "name" file.txt | awk '{print $2}')
          namespace=$(grep "namespace" file.txt | awk '{print $2}')
 
          # Update PR description with extracted values
          sed -i "s/{NAME}/${name}/g" $GITHUB_EVENT_PATH
          sed -i "s/{NAMESPACE}/${namespace}/g" $GITHUB_EVENT_PATH
 
          # Get PR number
          PR_NUMBER=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
          # Update PR body using GitHub API
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER} \
            -d "{\"body\": \"Updated PR body with values extracted from file:\n\n- Name: ${name}\n- Namespace: ${namespace}\"}"
