name: PR Check

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check label and description
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          LABELS=$(curl --silent --show-error --location --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/labels" | jq -r '.[].name')
          DESCRIPTION=$(curl --silent --show-error --location --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER" | jq -r '.body')

          if [[ $LABELS =~ "sanity-testing" ]] && [[ -n $DESCRIPTION ]]; then
            echo "Checks passed"
          else
            echo "Checks failed"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
