name: PR Label Trigger
 
on:
  pull_request:
    types: [labeled]
 
jobs:
  label_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR has specific label
        if: ${{ contains(github.event.pull_request.labels.*.name, 'regression-test') }}
        run: |
          # Your workflow steps here
          echo "The PR has the specified label. Triggering actions..."
 
      - name: Fail if label is not present
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'regression-test') }}
        run: |
          echo "The PR does not have the specified label. Failing workflow..."
          exit 1
