name: Label and PR Description Check

on:
  pull_request:
    types: [opened, reopened]

jobs:
  check-label-and-description:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check Label and PR Description
      id: label_and_description_check
      run: |
        # Check if the PR has the desired label
        if [[ $(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels" \
          | jq -r '.[].name' | grep -c "Sanity Testing") -eq 0 ]]; then
          echo "Desired label not found on the PR. Failing workflow."
          exit 1
        fi

        # Check if the PR has a description
        PR_DESCRIPTION=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}" \
          | jq -r '.body')
        if [[ -z $PR_DESCRIPTION ]]; then
          echo "PR description is missing. Failing workflow."
          exit 1
        fi

    - name: Execute Workflow
      if: ${{ steps.label_and_description_check.outcome == 'success' }}
      run: |
        # Add your workflow steps here
        echo "Label and PR description present. Workflow executed."
