name: Check PR Body

on:
  pull_request:
    types: [opened]

jobs:
  check-body:
    runs-on: ubuntu-latest
    steps:
    - name: Check for name
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const body = github.context.payload.pull_request.body
          const name = body.match(/name:\s*\*(.+)\*/i)
          if (!name || !name[1]) {
            throw new Error('Name is missing in the PR body')
          }
