name: "PR Label Validation"
on:
  pull_request:
    types:
      - opened
      - labeled

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate labels
        run: |
          REQUIRED_LABELS=("Regression Testing")  # Replace with your required labels
          PR_NUMBER=${{ github.event.pull_request.number }}
          LABELS_JSON=$(gh pr view $PR_NUMBER --json labels -q '.labels[].name')
          for LABEL in "${REQUIRED_LABELS[@]}"; do
            if ! echo "$LABELS_JSON" | grep -q "$LABEL"; then
              echo "error: required label \"$LABEL\" is missing."
              exit 1
            fi
