name: PR Check

on:
  pull_request:
    types: [opened]
    
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check label and description
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          LABELS=$(curl --silent --show-error --location --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/labels" | jq -r '.[].name')
          DESCRIPTION=$(curl --silent --show-error --location --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER" | jq -r '.body')
          if [[ $LABELS =~ "Sanity Testing" ]] && [[ -n $DESCRIPTION ]]; then
            echo "Checks passed"
          else
            echo "Checks failed"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get PR body
        id: pr
        run: |
          PR_BODY=$(gh pr view https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }} --json body -q '.body')
          echo "::set-output name=body::$PR_BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate PR body
        run: |
          REQUIRED_VALUES=("name" "namespace")
          for value in "${REQUIRED_VALUES[@]}"; do
            if ! echo "${{ steps.pr.outputs.body }}" | grep -q "$value"; then
              echo "Error: '$value' not found in PR body."
              exit 1
            fi
          done
          echo "All required values found in PR body."
